"""calendarjam — command station.

Mobile-first daily dashboard. Priority order: attention items → today (with
insights) → decisions → look-ahead → to-dos → the week. Reads from the repo:
  - dashboard.json        (week agenda + horizon, written by sync)
  - pending_events.json   (review queue — interactive)
  - app_open_items.json   (to-do / open-logistics checklist — interactive)
  - activity_log.json     (recent decisions)

Daily insights are generated by a rules engine (free, instant). There is a
clean hook (`_llm_insights`) to upgrade to a real LLM later: set an
ANTHROPIC_API_KEY secret and implement that one function.

Streamlit Cloud secrets: GITHUB_TOKEN, GITHUB_REPO.
"""

from __future__ import annotations

import base64
import json
from datetime import datetime, timezone

import requests
import streamlit as st

REPO = st.secrets.get("GITHUB_REPO", "esttt-blip/calendarjam")
TOKEN = st.secrets["GITHUB_TOKEN"]
BRANCH = "main"
API_BASE = f"https://api.github.com/repos/{REPO}/contents"
HEADERS = {
    "Authorization": f"Bearer {TOKEN}",
    "Accept": "application/vnd.github+json",
    "X-GitHub-Api-Version": "2022-11-28",
}

DEFAULT_OPEN_ITEMS = [
    {"id": "milo-boarding", "title": "🐶 Milo boarding — Alaska cruise Jul 8–19",
     "sub": "Pet Grand Hotel unavailable. Confirm Giving Tree K9 does overnight (571-799-8100).", "done": False},
    {"id": "camp-w5", "title": "🏕️ Henry camp — Week 5 (Jul 20–24)",
     "sub": "First week after the cruise. TBD.", "done": False},
    {"id": "camp-w8", "title": "🏕️ Henry camp — Week 8 (Aug 10–14)",
     "sub": "First week back from Germany. TBD.", "done": False},
    {"id": "camp-w9", "title": "🏕️ Henry camp — Week 9 (Aug 17–21)",
     "sub": "Bridge week before Code Ninjas. TBD.", "done": False},
    {"id": "thrills-reg", "title": "📝 Summertime Thrills registration (Week 6)",
     "sub": "Register via Arlington Rec — vaarlingtonweb.myvscloud.com", "done": False},
]


# ─────────────────────────── github i/o ───────────────────────────


def fetch_file(path: str):
    r = requests.get(f"{API_BASE}/{path}", headers=HEADERS, params={"ref": BRANCH}, timeout=15)
    if r.status_code == 404:
        return None, None
    r.raise_for_status()
    data = r.json()
    return json.loads(base64.b64decode(data["content"]).decode("utf-8")), data["sha"]


def write_file(path: str, content_obj, sha, message: str) -> None:
    body = {
        "message": message,
        "content": base64.b64encode(json.dumps(content_obj, indent=2).encode()).decode(),
        "branch": BRANCH,
    }
    if sha:
        body["sha"] = sha
    requests.put(f"{API_BASE}/{path}", headers=HEADERS, json=body, timeout=15).raise_for_status()


def log_activity(action: str, title: str, source: str = "") -> None:
    entry = {"ts": datetime.now(timezone.utc).isoformat(), "action": action,
             "title": title[:120], "source": source}
    try:
        log, sha = fetch_file("activity_log.json")
        log = (log or []) + [entry]
        write_file("activity_log.json", log[-500:], sha, f"app: log {action}")
    except Exception:
        pass


def clear_item(item, pending):
    synced, ssha = fetch_file("synced_events.json")
    synced = synced or []
    if item["id"] not in synced:
        synced.append(item["id"]); synced.sort()
    write_file("synced_events.json", synced, ssha, f"app: {item['id'][:8]}")
    _, psha = fetch_file("pending_events.json")
    write_file("pending_events.json", [p for p in pending if p["id"] != item["id"]],
               psha, f"app: clear {item.get('title','')[:30]}")


# ─────────────────────────── insights engine ───────────────────────────
# Each insight is (icon, text, severity) where severity ∈ {ok, info, warn}.


def _parse(iso):
    try:
        return datetime.fromisoformat(iso)
    except Exception:
        return None


def _llm_insights(day: dict):
    """Hook for a future LLM upgrade. Return a list of (icon, text, sev) or None.

    To enable later: add an ANTHROPIC_API_KEY secret, call the API here with the
    day's events, and return richer free-form insights. Until then this returns
    None and the rules engine below is used.
    """
    return None


def day_insights(day: dict):
    out = []
    events = day.get("events", [])
    timed = [e for e in events if not e.get("all_day") and not e.get("is_drive")]
    drives = [e for e in events if e.get("is_drive")]

    for c in day.get("conflicts", []):
        out.append(("⚠️", f"Conflict: {c['a']} vs {c['b']}", "warn"))

    n = len(timed)
    if n == 0 and not day.get("conflicts"):
        out.append(("🟢", "Open day — nothing scheduled", "ok"))
    elif n >= 4:
        out.append(("🔴", f"Packed — {n} commitments", "warn"))
    elif n >= 1:
        out.append(("📋", f"{n} thing{'s' if n != 1 else ''} on", "info"))

    # Start times (we only have starts, so flag back-to-back starts)
    starts = sorted([(_parse(e["sort"]), e) for e in timed if _parse(e.get("sort", ""))],
                    key=lambda x: x[0])
    for i in range(len(starts) - 1):
        gap = (starts[i + 1][0] - starts[i][0]).total_seconds() / 60
        if 0 < gap <= 60:
            out.append(("⏱", f"Back-to-back: {starts[i][1]['title'][:22]} → "
                             f"{starts[i+1][1]['title'][:22]} ({int(gap)}m)", "warn"))
            break

    if starts:
        first_h = starts[0][0].hour
        if first_h < 8:
            out.append(("⏰", f"Early start — {starts[0][1]['time']}", "info"))
        last_h = starts[-1][0].hour
        if n >= 2 and last_h < 17:
            out.append(("🌙", "Evening's free", "ok"))

    if len(drives) >= 3:
        out.append(("🚗", f"{len(drives)} drives — lots of running around", "info"))

    dw = day.get("weather") or {}
    if dw:
        if dw.get("precip_pct", 0) >= 50:
            out.append(("🌧", "Rain likely — plan indoor / umbrella", "info"))
        if dw.get("high_f", 0) >= 88:
            out.append(("🥵", f"Hot ({dw.get('high_f')}°) — hydrate", "info"))

    return out


def lookahead_insights(week, horizon, open_items):
    out = []
    for b in horizon.get("birthdays", []):
        when = "today" if b["days_out"] == 0 else f"in {b['days_out']}d"
        out.append(("🎂", f"{b['title']} — {b['day']} ({when}). Plan a gift/card.", "info"))
    for h in horizon.get("holidays", []):
        out.append(("🎉", f"{h['title']} — {h['day']}", "ok"))

    # Busiest upcoming day (excludes today = week[0])
    busiest, best = None, 0
    for d in week[1:]:
        cnt = len([e for e in d.get("events", []) if not e.get("all_day") and not e.get("is_drive")])
        if cnt > best:
            best, busiest = cnt, d
    if busiest and best >= 3:
        out.append(("🔭", f"Busiest day ahead: {busiest['label']} ({best} things)", "warn"))

    # Any conflicts across the week
    conflict_days = [d["label"] for d in week if d.get("conflicts")]
    if conflict_days:
        out.append(("⚠️", f"Conflicts to resolve: {', '.join(conflict_days[:3])}", "warn"))

    open_todo = [it for it in open_items if not it.get("done")]
    if open_todo:
        out.append(("📌", f"{len(open_todo)} open to-do{'s' if len(open_todo) != 1 else ''} "
                         f"(e.g. {open_todo[0]['title'].split('—')[0].strip()})", "info"))
    return out


def insights_for(day):
    return _llm_insights(day) or day_insights(day)


def _chips(insights) -> str:
    if not insights:
        return ""
    html = "<div class='chips'>"
    for icon, text, sev in insights:
        html += f"<span class='chip chip-{sev}'>{icon} {text}</span>"
    return html + "</div>"


# ─────────────────────────── page setup ───────────────────────────

st.set_page_config(page_title="calendarjam", page_icon="📅", layout="centered",
                   initial_sidebar_state="collapsed")

st.markdown("""
<style>
  :root { color-scheme: light; }
  .block-container { padding-top: 1.1rem; padding-bottom: 3rem; max-width: 760px; }

  .sec { font-size:11px; font-weight:800; letter-spacing:.07em; text-transform:uppercase;
         color:#9398a8; margin:20px 0 8px; }

  .card { background:#fff; border:1px solid #ececf2; border-radius:16px; padding:14px 16px;
          box-shadow:0 1px 3px rgba(20,20,40,.05); margin-bottom:10px; }
  .today-card { border:1.5px solid #1a1a2e; }
  .day-head { font-weight:750; color:#1a1a2e; font-size:14px; margin-bottom:6px; }
  .ev-row { display:flex; gap:10px; padding:4px 0; border-top:1px solid #f4f4f7; }
  .ev-row.first { border-top:none; }
  .ev-time { width:68px; flex-shrink:0; color:#5b5b6b; font-weight:600;
             font-family:ui-monospace,monospace; font-size:12px; }
  .ev-title { color:#222; font-size:13.5px; line-height:1.35; }
  .ev-loc { color:#a6a6b2; font-size:11px; }
  .empty-day { color:#c4c4cf; font-size:12.5px; font-style:italic; }

  .chips { display:flex; flex-wrap:wrap; gap:6px; margin-top:10px; }
  .chip { font-size:11px; font-weight:600; padding:3px 9px; border-radius:20px; line-height:1.35; }
  .chip-ok   { background:#e9f7ef; color:#1c7a46; }
  .chip-info { background:#eef2fb; color:#34508f; }
  .chip-warn { background:#fdeee8; color:#b4471f; }

  .attention { background:linear-gradient(135deg,#fff4f0,#ffe9e0); border:1px solid #ffd9c9;
               border-radius:14px; padding:11px 15px; margin-bottom:6px; font-size:13px; color:#8a3a1a; }

  .week-grid { display:grid; grid-template-columns:repeat(auto-fill,minmax(220px,1fr)); gap:12px; }
  .wk-card { background:#fff; border:1px solid #ececf2; border-radius:14px; padding:11px 13px;
             box-shadow:0 1px 3px rgba(20,20,40,.04); }

  .look-row { padding:7px 0; font-size:13.5px; color:#333; border-top:1px solid #f4f4f7; line-height:1.4; }
  .look-row.first { border-top:none; }
  .todo-sub { font-size:11px; margin:0 0 8px 28px; color:#9a9aa7; }
  .muted { color:#a6a6b2; font-size:11.5px; }
  div[data-testid="stCheckbox"] { margin-bottom:0; }
</style>
""", unsafe_allow_html=True)

dash, _ = fetch_file("dashboard.json")
pending, _ = fetch_file("pending_events.json")
activity_log, _ = fetch_file("activity_log.json")
open_items, open_sha = fetch_file("app_open_items.json")
pending = pending or []
activity_log = activity_log or []
if open_items is None:
    open_items = DEFAULT_OPEN_ITEMS

theme = (dash or {}).get("theme") or {"emoji": "📅", "title": "", "blurb": "",
                                      "color1": "#1a1a2e", "color2": "#3a3a55"}
w = (dash or {}).get("weather") or {}
week = (dash or {}).get("week", [])
horizon = (dash or {}).get("horizon", {})

all_conflicts = []
for day in week:
    for c in day.get("conflicts", []):
        all_conflicts.append({**c, "day": day["label"]})


def _day_card_inner(day: dict) -> str:
    rows = ""
    evs = day.get("events", [])
    if evs:
        for i, e in enumerate(evs):
            loc = f"<div class='ev-loc'>📍 {e['location'][:40]}</div>" if e.get("location") else ""
            first = " first" if i == 0 else ""
            rows += (f"<div class='ev-row{first}'><div class='ev-time'>{e['time']}</div>"
                     f"<div><div class='ev-title'>{e['title']}</div>{loc}</div></div>")
    else:
        rows = "<div class='empty-day'>nothing scheduled</div>"
    return rows


# ─────────────────────────── header ───────────────────────────

st.markdown(
    f"<div style='height:6px;border-radius:6px;margin-bottom:12px;"
    f"background:linear-gradient(90deg,{theme['color1']},{theme['color2']})'></div>",
    unsafe_allow_html=True,
)
wx = (f"<span class='muted'>&nbsp;&nbsp;{w.get('emoji','')} {w.get('high_f','–')}°/{w.get('low_f','–')}°"
      f"·{w.get('precip_pct',0)}%</span>") if w else ""
chip = (f"<span style='margin-left:9px;background:linear-gradient(135deg,{theme['color1']},{theme['color2']});"
        f"color:#fff;font-size:11px;font-weight:700;padding:3px 10px;border-radius:13px'>"
        f"{theme['emoji']} {theme['title']}</span>") if theme.get("title") else ""
st.markdown(
    f"<div style='display:flex;align-items:center;flex-wrap:wrap'>"
    f"<span style='font-size:24px;font-weight:800;color:#1a1a2e'>📅 calendarjam</span>{chip}{wx}</div>"
    + (f"<div class='muted' style='margin-top:2px'>{theme['blurb']}</div>" if theme.get("blurb") else ""),
    unsafe_allow_html=True,
)

if not dash:
    st.warning("No dashboard snapshot yet — the next 6 AM sync will populate this.", icon="⏳")

# ─────────────────────────── 1. attention strip ───────────────────────────

n_pending = len(pending)
if all_conflicts or n_pending:
    bits = []
    if all_conflicts:
        bits.append(f"⚠️ {len(all_conflicts)} conflict{'s' if len(all_conflicts) != 1 else ''}")
    if n_pending:
        bits.append(f"✅ {n_pending} to review")
    st.markdown(f"<div class='attention'><b>Heads up</b> &nbsp;·&nbsp; {' &nbsp;·&nbsp; '.join(bits)}</div>",
                unsafe_allow_html=True)

# ─────────────────────────── 2. today (+ insights) ───────────────────────────

st.markdown("<div class='sec'>📌 Today</div>", unsafe_allow_html=True)
if week:
    today = week[0]
    st.markdown(
        f"<div class='card today-card'><div class='day-head'>{today['label']}</div>"
        f"{_day_card_inner(today)}{_chips(insights_for(today))}</div>",
        unsafe_allow_html=True)
else:
    st.info("Agenda will appear after the next sync.")

# ─────────────────────────── 3. needs you ───────────────────────────

st.markdown("<div class='sec'>✅ Needs you</div>", unsafe_allow_html=True)
if not pending and not all_conflicts:
    st.success("All clear — nothing needs you right now.")
for c in all_conflicts:
    with st.container(border=True):
        st.markdown(f"⚠️ **Conflict — {c['day']}**")
        st.markdown(f"<div style='font-size:13px;color:#444'><b>{c['a']}</b> ({c['a_time']})"
                    f" &nbsp;vs&nbsp; <b>{c['b']}</b> ({c['b_time']})</div>", unsafe_allow_html=True)
        st.caption("Resolve by removing one in your calendar.")
for idx, item in enumerate(pending):
    title = item.get("title", "(untitled)")
    source = item.get("source", "")
    sender = item.get("from", "").split("<")[0].strip().strip('"') or "—"
    desc = (item.get("description") or "").replace("\r", "").strip()
    if len(desc) > 170:
        desc = desc[:170] + "…"
    with st.container(border=True):
        st.markdown(f"**{title}**")
        st.caption(f"{source} · from {sender}")
        if desc:
            st.markdown(f"<div style='color:#555;font-size:13px;line-height:1.5'>{desc}</div>",
                        unsafe_allow_html=True)
        b1, b2, _ = st.columns([1, 1, 2])
        if b1.button("✓ Got it", key=f"y{idx}", type="primary", use_container_width=True):
            clear_item(item, pending); log_activity("acked", title, source); st.rerun()
        if b2.button("✗ Skip", key=f"n{idx}", use_container_width=True):
            clear_item(item, pending); log_activity("dismissed", title, source); st.rerun()

# ─────────────────────────── 4. look-ahead ───────────────────────────

la = lookahead_insights(week, horizon, open_items)
if la:
    st.markdown("<div class='sec'>🔭 Look ahead</div>", unsafe_allow_html=True)
    rows = ""
    for i, (icon, text, sev) in enumerate(la):
        first = " first" if i == 0 else ""
        rows += f"<div class='look-row{first}'>{icon} {text}</div>"
    st.markdown(f"<div class='card'>{rows}</div>", unsafe_allow_html=True)

# ─────────────────────────── 5. to-do ───────────────────────────

st.markdown("<div class='sec'>📋 To-do · open items</div>", unsafe_allow_html=True)
with st.container(border=True):
    changed = False
    for it in open_items:
        done = it.get("done", False)
        label = f"~~{it['title']}~~  ✅" if done else it["title"]
        new_val = st.checkbox(label, value=done, key="oi_" + it["id"])
        if it.get("sub"):
            sub_color = "#cccdd6" if (new_val or done) else "#9a9aa7"
            st.markdown(f"<div class='todo-sub' style='color:{sub_color}'>{it['sub']}</div>",
                        unsafe_allow_html=True)
        if new_val != done:
            it["done"] = new_val
            changed = True
    if changed:
        try:
            write_file("app_open_items.json", open_items, open_sha, "app: update to-do items")
            st.toast("Saved ✓", icon="✅")
        except Exception:
            st.toast("Couldn't save — try again", icon="⚠️")
        st.rerun()

# ─────────────────────────── 6. the week ───────────────────────────

if len(week) > 1:
    st.markdown("<div class='sec'>🗓️ The week ahead</div>", unsafe_allow_html=True)
    cards = ""
    for day in week[1:]:
        cards += (f"<div class='wk-card'><div class='day-head'>{day['label']}</div>"
                  f"{_day_card_inner(day)}{_chips(insights_for(day))}</div>")
    st.markdown(f"<div class='week-grid'>{cards}</div>", unsafe_allow_html=True)

# ─────────────────────────── footer ───────────────────────────

with st.expander("📜 Recent activity"):
    if not activity_log:
        st.caption("No recent activity.")
    else:
        icons = {"added": "✓", "acked": "✓", "dismissed": "✗", "skipped": "✗"}
        for e in sorted(activity_log, key=lambda x: x.get("ts", ""), reverse=True)[:30]:
            try:
                d = datetime.fromisoformat(e["ts"]).astimezone().strftime("%b %-d")
            except Exception:
                d = "—"
            st.markdown(f"<div style='font-size:13px;color:#555;padding:1px 0'>"
                        f"<span style='color:#aaa'>{d}</span> &nbsp; "
                        f"{icons.get(e.get('action'),'·')} {e.get('title','')[:58]}</div>",
                        unsafe_allow_html=True)

st.divider()
fc1, fc2 = st.columns([3, 1])
with fc1:
    synced_txt = (f"🔄 Last synced {dash['generated_label']}" if dash and dash.get("generated_label")
                  else "🔄 Awaiting first sync")
    st.caption(f"{synced_txt} · runs 6 AM ET daily")
with fc2:
    if st.button("🔄 Refresh", use_container_width=True):
        st.rerun()
